# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1

matrix:
  allow_failures:
    - julia: nightly

addons:
  apt: # apt-get for linux
    packages:
    - liblapack-dev
    - libblas-dev

notifications:
  email: false
before_script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="MathOptInterface", rev="master"))'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="SemidefiniteOptInterface", rev="bl/moiv0.9"))'
after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
