# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
os:
  - linux
  - osx
julia:
  - 1.0
  - 1

matrix:
  allow_failures:
    - julia: nightly

addons:
  apt: # apt-get for linux
    packages:
    - liblapack-dev
    - libblas-dev

notifications:
  email: false
