# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly

addons:
  apt: # apt-get for linux
    packages:
    - liblapack-dev
    - libblas-dev

before_script:
  - julia -e 'Pkg.clone("https://github.com/JuliaOpt/MathOptInterface.jl.git")'
  - julia -e 'Pkg.clone("https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl.git")'
  - julia -e 'Pkg.clone("https://github.com/JuliaOpt/MathOptInterfaceTests.jl.git")'
  - julia -e 'Pkg.clone("https://github.com/JuliaOpt/SemidefiniteOptInterface.jl.git")'

notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("CSDP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("CSDP")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
