# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly

addons:
  apt: # apt-get for linux
    packages:
    - liblapack-dev
    - libblas-dev

notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.init(); Pkg.clone("https://github.com/JuliaOpt/MathOptInterface.jl.git"); Pkg.clone("https://github.com/JuliaOpt/SemidefiniteOptInterface.jl.git"); Pkg.clone(pwd()); Pkg.build("CSDP"); Pkg.test("CSDP"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("CSDP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("CSDP")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
